perkss:
  kafka:
    example:
      bootstrap-servers: "localhost:9093,localhost:9094,localhost:9095" # try different variations, provide all, and provide docker names
      input-topic: "lowercase-topic"


      # different ports for SSL and Non SSL
